### ISSUE TITLE
Console messages don't come up when running tests

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-common#6]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/6)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------

**Comment by chapulina** [comment]
I think this issue is outdated. The new behaviour is to write `ignerr` by default, and other logging levels can be enabled with `SetVerbosity(N)`. I added an example in https://github.com/ignitionrobotics/ign-common/pull/106

When running tests, the verbosity can be increased in the beginning of the test, for example like [this](https://github.com/ignitionrobotics/ign-gazebo/blob/80cbc2ee0885cfa4ecebbca301916f5f74b8a4ca/src/Component_TEST.cc#L36-L42).
